# Generated by Django 5.2 on 2025-04-21 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_answer',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_option',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
