# Generated by Django 5.2 on 2025-04-21 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_useranswer_selected_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='quiz_session',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
