# Generated by Django 5.2 on 2025-04-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_useranswer_quiz_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.CharField(default='A', max_length=200),
            preserve_default=False,
        ),
    ]
