# Generated by Django 5.2 on 2025-04-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='quiz_session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
